version: 1.0.{build}
image: Visual Studio 2017
configuration:
- Release
- Debug
platform:
- x64
- Win32
shallow_clone: true
before_build:
- ps: .\scripts\premake5.exe --file=scripts\premake5.lua vs2017
build:
  project: FluxEngine_vs2017.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: '\FluxEngine\Resources'
  name: Resources
- path: '\Build\FluxGame_$(platform)_$(configuration)'
  name: Build