version: 1.0.{build}
image: Visual Studio 2017
configuration:
- Release
- Debug
platform:
- x64
- Win32
shallow_clone: true
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
environment:
  appveyor_rdp_password:
    secure: isPeZD3/K+h+07yX2nK8kQ==
before_build:
- ps: .\scripts\MakeVS2017.bat
after_build:
- cmd: >-
    .\FluxPak\CreateResponseFile.bat

    .\FluxPak\CreatePakFile.bat "C:/Projects/FluxEngine/"

    7z a Artifacts.zip .\Build\FluxGame_$(platform)_$(configuration)\* .\FluxGame\Resources.pak .\FluxGame\Resources
build:
  project: FluxEngine_vs2017.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: 'Artifacts.zip'
  name: Build_$(platform)_$(configuration)