version: 1.0.{build}
image: Visual Studio 2017
configuration:
- Release
- Debug
platform:
- x64
- Win32
clone_folder: C:\FluxEngine
shallow_clone: true
before_build:
- ps: .\scripts\MakeVS2017.bat
after_build:
- cmd: >-
    FluxPak\CreateResponseFile.bat

    FluxPak\CreatePakFile.bat C:/FluxEngine/FluxGame/Resources
build:
  project: FluxEngine_vs2017.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: '\FluxGame\Resources'
  name: Resources
- path: '\FluxGame\Resources.pak'
  name: PakFile
- path: '\Build\FluxGame_$(platform)_$(configuration)'
  name: Build_$(platform)_$(configuration)