version: 1.0.{build}
image: Visual Studio 2017
configuration:
- Release
- Debug
platform:
- x64
- Win32
shallow_clone: true
before_build:
- ps: .\scripts\MakeVS2017.bat
after_build:
- ps: 7z a "Game.zip" "%APPVEYOR_BUILD_FOLDER%\Build\FluxGame_$(platform)_$(configuration)\" "%APPVEYOR_BUILD_FOLDER%\Build\FluxEngine_$(platform)_$(configuration)\"
build:
  project: FluxEngine_vs2017.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: '\FluxGame\Resources'
  name: Resources
- path: 'Game.zip'
  name: Build_$(platform)_$(configuration)