version: 1.0.{build}
image: Visual Studio 2017
configuration:
- Release
- Debug
platform:
- x64
- Win32
shallow_clone: true
before_build:
- ps: .\scripts\premake5.exe --file=scripts\premake5.lua vs2017
build:
  project: FluxEngine_vs2017.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: '\FluxEngine\Resources'
  name: Resources
- path: '\Build\FluxEngine_x86_Release'
  name: FluxEngine_x86_Release
- path: '\Build\FluxEngine_x64_Release'
  name: FluxEngine_x64_Release
- path: '\Build\FluxEngine_x86_Debug'
  name: FluxEngine_x86_Debug
- path: '\Build\FluxEngine_x64_Debug'
  name: FluxEngine_x64_Debug
notifications:
- provider: Email
  to:
  - sim2.coenen@gmail.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false