version: 1.0.{build}
image: Visual Studio 2017
configuration:
- Debug
platform:
- x64
- Win32
shallow_clone: true
before_build:
- ps: .\scripts\premake5.exe --file=scripts\premake5.lua vs2017
build_script:
- ps: >-
    Write-Output "Configuration: $env:CONFIGURATION"

    Write-Output "Platform: $env:PLATFORM"

    msbuild /v:m /p:"Configuration=$env:CONFIGURATION" /p:Platform="$env:PLATFORM" "$env:Solution" /p:DefineConstants="CI" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
build:
  project: FluxEngine.sln
  parallel: false
  verbosity: minimal
artifacts:
- path: '\FluxEngine\Resources'
  name: Resources
- path: '\Build\FluxEngine_Win32_Release'
  name: FluxEngine_x86_Release
- path: '\Build\FluxEngine_x64_Release'
  name: FluxEngine_x64_Release
- path: '\Build\FluxEngine_Win32_Debug'
  name: FluxEngine_x86_Debug
- path: '\Build\FluxEngine_x64_Debug'
  name: FluxEngine_x64_Debug