version: 1.0.{build}
image: Visual Studio 2017
configuration:
- Release
- Debug
platform:
- x64
- Win32
shallow_clone: true
before_build:
- ps: >-
    .\scripts\MakeVS2017.bat

    .\cloc-1.64.exe FluxEngine > CodeReport.txt
build:
  project: FluxEngine_vs2017.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: '\FluxEngine\Resources'
  name: Resources
- path: '\Build\FluxGame_$(platform)_$(configuration)'
  name: Build
- path: 'CodeReport.txt'
  name: CodeReport